"""empty message

Revision ID: 4255112d591c
Revises: cc142b681b9d
Create Date: 2023-07-12 18:37:14.883304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4255112d591c'
down_revision = 'cc142b681b9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('use', sa.String(length=300), nullable=True))
        batch_op.drop_constraint('ships_ship_crew_key', type_='unique')
        batch_op.create_unique_constraint(None, ['use'])
        batch_op.create_unique_constraint(None, ['model'])
        batch_op.drop_column('ship_crew')
        batch_op.drop_column('year_old')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_old', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ship_crew', sa.VARCHAR(length=400), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('ships_ship_crew_key', ['ship_crew'])
        batch_op.drop_column('use')
        batch_op.drop_column('model')

    # ### end Alembic commands ###
