"""empty message

Revision ID: 9c057af83c0f
Revises: f76fbdc7da4c
Create Date: 2023-07-12 17:12:27.145912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c057af83c0f'
down_revision = 'f76fbdc7da4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('eye_color',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('eye_color',
               existing_type=sa.String(length=80),
               type_=sa.BOOLEAN(),
               existing_nullable=False)

    # ### end Alembic commands ###
